---
- block:
    - name: Install NodeJS
      get_url:
        url: https://deb.nodesource.com/setup_10.x
        dest: /tmp/
    - shell: bash /tmp/setup_10.x
    - package:
        name: nodejs
        state: present
    - npm: name=yarn global=yes
  become: yes
  become_user: root

- block:
    - name: Install pre-requisite packages
      become: yes
      become_user: root
      package:
        name: ['git', 'curl', 'wget', 'cron', 'supervisor', 'nginx', 'zlib1g-dev', 'libssl-dev', 'python-openssl']
        state: present
    - name: Install Python3.6
      get_url:
        url: https://www.python.org/ftp/python/3.6.10/Python-3.6.10.tar.xz
        dest: /tmp/python-3.6.tar.xz
    - unarchive:
        src: /tmp/python-3.6.tar.xz
        dest: /tmp/
        remote_src: yes
    - shell: |
        cd /tmp/Python-3.6.10
        ./configure && make && make install
  become: yes

- block:
    - name: add redis-server apt repo
      apt_repository:
        repo: ppa:chris-lea/redis-server
    - name: Install redis-server
      package:
        name: redis-server
        state: present
    - name: Start redis-Server
      shell: /etc/init.d/redis-server start

- name: Create new non-root user
  user:
    name: "{{ userName }}"
    shell: /bin/bash
    home: "/home/{{ userName }}"

- name: cd into directory and git clone bench
  git:
    repo: https://github.com/frappe/bench
    dest: "/home/{{ userName }}/bench"

- name: Install Bench app
  pip:
    name: bench
    executable: pip3.6
    extra_args: -e
    chdir: "/home/{{ userName }}"

- name: bench init
  become: yes
  become_user: "{{ userName }}"
  shell: "bench init --python /usr/local/bin/python3.6 {{ bench_name }}"
  args:
    chdir: "/home/{{ userName }}"
    executable: /bin/bash

#- name: Get erpnext app
#  become: yes
#  become_user: "{{ userName }}"
#  shell: bench get-app erpnext https://github.com/frappe/erpnext
#  args:
#    chdir: "/home/{{ userName }}/{{ bench_name }}"

- name: Create site
  become: yes
  become_user: "{{ userName }}"
  shell: |
    bench set-mariadb-host {{ dbhost }}
    bench new-site {{ siteName }} --db-host {{ dbhost }} --db-name {{ dbname }} --mariadb-root-username {{ dbuser }} --mariadb-root-password {{ dbpass }} --admin-password {{ adminPass }} --install-app erpnext --force
  args:
    chdir: "/home/{{ userName }}/{{ bench_name }}"

- name: Bench setup production
  become: yes
  become_user: root
  shell: bench setup production {{ userName }}
  args:
    chdir: "/home/{{ userName }}/{{ bench_name }}"

- name: start supervisorctl
  become: yes
  become_user: root
  supervisorctl:
    name: ALL
    state: started
