---
- name: Install common packages
  package:
    name: ['build-essential', 'sudo', 'locales']
    state: present

- name: Ansible key file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
