---
- name: Install python3
  package:
    name: ['python3', 'python3-pip', 'python3-setuptools', 'build-essential', 'sudo']
    state: present

- name: Ansible key file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
